spring:
  datasource:
    url: jdbc:postgresql://localhost:5402/orderdb?options=-c%20TimeZone=Asia/Kolkata
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
