version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container-cart
    restart: always
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: cartDB
    ports:
      - "5401:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: