services:
  postgres:
    image: postgres:16
    container_name: postgres-container-inventory
    restart: always
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: inventorydb
    ports:
      - "5403:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: